-- Table structure for table 'comments'
CREATE TABLE IF NOT EXISTS public.comments
(
	comment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	comment_text text NOT NULL,
	comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	account_id integer NOT NULL,
	inv_id integer NOT NULL,
	CONSTRAINT comment_pkey PRIMARY KEY (comment_id)
);

-- Create relationship between 'comments' and 'account' tables
ALTER TABLE IF EXISTS public.comments
	ADD CONSTRAINT fk_account FOREIGN KEY (account_id)
	REFERENCES public.account (account_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Create relationship between 'comments' and 'inventory' tables
ALTER TABLE IF EXISTS public.comments
	ADD CONSTRAINT fk_inv FOREIGN KEY (inv_id)
	REFERENCES public.inventory (inv_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;